version: '3.8'

services:
  app:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - .:/src
      - cargo_home:/usr/local/cargo
    command: /bin/sh -c "while sleep 1000; do :; done"
volumes:
  cargo_home:
